name: Pre-build Dev Container (Single Runner)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: ${{github.repository_owner}}/hugo-blog-dc
  REGISTRY: ghcr.io
jobs:        
  build-image:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      packages: write
      # id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            { "features": { "containerd-snapshotter": true } }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build!
        run: |
          sudo npm install -g npm@latest
          npm install -g @devcontainers/cli
          export HUGO_VERSION=$(sed -e 's/\/\/.*//' -e 's/\/\*.*\*\///' .devcontainer/build/devcontainer.json | jq -r '.features["ghcr.io/devcontainers/features/hugo:1"].version')
          export PWSH_VERSION=$(sed -e 's/\/\/.*//' -e 's/\/\*.*\*\///' .devcontainer/build/devcontainer.json | jq -r '.features["ghcr.io/devcontainers/features/powershell:1"].version')
          export NODE_VERSION=$(sed -e 's/\/\/.*//' -e 's/\/\*.*\*\///' .devcontainer/build/devcontainer.json | jq -r '.features["ghcr.io/devcontainers/features/node:1"].version')         
          export IMAGE_NAME="${REGISTRY}/${BASE_IMAGE_NAME}:${HUGO_VERSION}"

          devcontainer build --workspace-folder . --push true --image-name "${IMAGE_NAME}" --image-name "${REGISTRY}/${BASE_IMAGE_NAME}:latest" \
            --platform linux/amd64,linux/arm64 \
            --config '.devcontainer/build/devcontainer.json' \
            --label "index:org.opencontainers.image.created=$(date --rfc-3339=seconds --utc)" \
            --label "index:org.opencontainers.image.source=${GITHUB_REPOSITORY_URL}"\
            --label "index:org.opencontainers.image.version=${HUGO_VERSION}" \
            --label "index:org.opencontainers.image.ref.name=${GITHUB_REF}" \
            --label "index:org.opencontainers.image.name=Hugo ${HUGO_VERSION} Dev Container" \
            --label "index:org.opencontainers.image.description=Hugo ${HUGO_VERSION}; PowerShell ${PWSHL_VERSION}; Node: ${NODE_VERSION}" \
            --label "index:org.opencontainers.image.revision=${{ github.event.pull_request.head.sha }}"
      
          #docker image push --all-tags "${REGISTRY}/${BASE_IMAGE_NAME}"
